name: Test
on: [pull_request]

jobs:
  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

  # codecov:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Cache Composer dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: /tmp/composer-cache
  #         key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

  #     - uses: php-actions/composer@v5

  #     - uses: php-actions/phpunit@v2
  #       env:
  #         XDEBUG_MODE: coverage
  #       with:
  #         php_extensions: xdebug
  #         args: --coverage-clover coverage.xml

  #     - uses: codecov/codecov-action@v1
  #       with:
  #         file: ./coverage.xml
  #         fail_ci_if_error: true
  #         verbose: true

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
        - 7.1
        - 7.2
        - 7.3
        - 7.4
        - 8.0
        include:
          - php: 7.1
            phpunit: 7.5.20
          - php: 7.2
            phpunit: 8.5.13
          - php: 7.3
            phpunit: 9.5.0
          - php: 7.4
            phpunit: 9.5.0
          - php: 8.0
            phpunit: 9.5.0

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php }}

      - uses: php-actions/phpunit@v2
        with:
          php_version: ${{ matrix.php }}
          version: ${{ matrix.phpunit }}
