name: Test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
        - 5.4
        - 5.5
        - 5.6
        - 7.3
        - 7.4
        - 8.0
        - hhvm
    steps:
      - uses: actions/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v2
        with:
          php_version: ${{ matrix.php }}
